version: '2'
services:
  ${appNameOriginal}-ha:
    image: rancher/lb-service-haproxy:v0.7.5
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.container.requested_ip: ${r'${RANCHER_FIXED_IP}'}
  ${appNameOriginal}:
    image: $HARBOR_URL/trinasolar/$IMAGE_NAME:$IMAGE_VERSION
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone
    mem_reservation: 1024000000
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
    labels:
      io.rancher.container.pull_image: always
